# Generated by Django 3.0.4 on 2021-05-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('n_connected', models.IntegerField(default=0)),
                ('n_demanded', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=50)),
                ('user_room_number', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(default='waiting', max_length=10)),
                ('num_cards', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'unique_together': {('user_name', 'room_name')},
            },
        ),
    ]
