# Generated by Django 3.0.4 on 2021-05-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='n_ready',
            field=models.IntegerField(default=0),
        ),
    ]
