# Generated by Django 3.0.4 on 2021-05-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
